groups:
- name: container_alerts
  rules:
  - alert: ContainerRestarting
    expr: delta(container_start_time_seconds{name!=""}[15m]) > 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Redémarrage du conteneur ({{ $labels.name }})"
      description: "Le conteneur {{ $labels.name }} a redémarré dans les 15 dernières minutes."
      
  - alert: ContainerCPUThrottling
    expr: rate(container_cpu_cfs_throttled_periods_total{name!=""}[5m]) / rate(container_cpu_cfs_periods_total{name!=""}[5m]) > 0.25
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "CPU Throttling du conteneur ({{ $labels.name }})"
      description: "Le conteneur {{ $labels.name }} a un CPU Throttling de {{ $value | humanizePercentage }}."