global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'server'
    static_configs:
      - targets: ['server:5000']

  - job_name: 'map'
    static_configs:
      - targets: ['map:5000']

  - job_name: cadvisor
    scrape_interval: 10s
    static_configs:
    - targets: ['cadvisor:8080']

rule_files:
   - ./rules/container_alerts.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:9093']
